server {
    listen 4200;
    server_name _;

    root /usr/share/nginx/html;

    # Archivos estáticos con cache
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # SPA routing - todo va a index.html
    location / {
        try_files $uri $uri/ /index.html =404;
    }
}
